### ISSUE TITLE
Referencing a document

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#153]
The first name and surname of the author are separate and both required for all documents. Where the publisher is the government (for example) this does not work. Can we have one AUTHOR field rather than the first name and surname?

**Comment by byndcivilization** [comment]
This is on purpose since we want to maintain the ability to change format of the citation. Having author name as a single text field kills that as well as any possible easy integration with a citation management platform. We can make the author field not required but again i need an updated list of required fields.

**Comment by byndcivilization** [comment]
@isabellee @ahasemann does this make sense? How do you want to proceed.

**Comment by isabellee** [comment]
Is it possible to have the author field as a required field, but have it be an optional choice between an individual (or several individual) authors or an entity? @byndcivilization

**Comment by byndcivilization** [comment]
@isabellee and @ahasemann we can use logic that says either author or some other entity. So maybe 'author' or 'institution'?

**Comment by byndcivilization** [comment]
This will be sorted in #169
