### ISSUE TITLE
Commenting as researcher

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#157]
Text formatting remain for published comments up until strikethrough. The others do not save when the comments are published. Maybe just remove them?

**Comment by byndcivilization** [comment]
can you give me more details? this is unclear

**Comment by isabellee** [comment]
So when adding a comment to an answer as a researcher, I was trying to format the text with the text functions. If you look at the line of text formatting functions:
1. From the left until strike-through - these formats would save once the comment was submitted.
2. From strike-through to the right - these would not save. I could use them in the text box and they would format the text in the box, but once I submitted the comment, they would not save when the comment appears above.

**Comment by byndcivilization** [comment]
okay i know what the issue is here. We need to decide what formatting we want to allow. there are the UI controls and the data model. Both of these can be restricted to only what we want to allow and currently dont match up. part of this is that the data model is currently pretty standard and minimal and the UI has been very adhoc. Do we have a sense of what we want to allow?

**Comment by isabellee** [comment]
Bold, italic, underline, bullet points, list numbers (1,2,3) quotation marks, clear formatting
