### ISSUE TITLE
Display answer history for admins

### ISSUE THREAD

**Issue by ahasemann** [NRGI/rgi-assessment-tool#207]
Admin view: If a consultant changes the answer score, the admin can only see the lastest one. Would it be possible to show the previous scores on the answer pages?

**Comment by byndcivilization** [comment]
@ahasemann We can do this but I really worry that things could get visually ugly. Maybe at the bottom or as a tab?

**Comment by byndcivilization** [comment]
To populate this we would call question history. Because we are storing every version of an answer (i.e. if a user comments or saves or adds a reference) this might make things a bit laggy. We should set up history specific controller and route to offload the heavy lifting server side. The function would need to pull full answer history, and parse through versions to only show changes in reviewer and researcher selection data. Create array, if answer data != previous answer data push. That would go for both selection and justification.

**Comment by ahasemann** [comment]
At the bottom or as a tab would be fine.

**Comment by byndcivilization** [comment]
Let's do it as a tab then. I'll move this to post launch.

**Comment by ahasemann** [comment]
Ok

**Comment by byndcivilization** [comment]
We need a tab for answer history. This should be similar to the guidance note tab. the tab should pull data from the researcher_score_history sub doc.
