### ISSUE TITLE
Duplicate email error when creating an interview reference

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#256]
I'm having this error when I try to create a reference by inserting a phone number instead of an email address. ![image](https://cloud.githubusercontent.com/assets/16592996/13494304/559fc2f8-e13b-11e5-88ec-9ee68e6e4447.png)

**Comment by byndcivilization** [comment]
Okay I think this is an issue with our data model. We need a way to make sure we don't end up with duplicate interviewees. In the db, the email field is unique which acts as a check. However since we aren't requiring email now, any blank email is seen as a duplicate. I really really don't want to get into the situation where we have 10 versions of each of 20 interviewees across 80 assessments. Names don't work because they're too easy to misspell. @alexander-elgin any ideas?

**Comment by byndcivilization** [comment]
should be fixed in next push.
