### ISSUE TITLE
Saving a document reference as Legislation

### ISSUE THREAD

**Issue by isabellee** [NRGI/rgi-assessment-tool#260]
When it is saved and appears under Citations, it says:
Type: Statute

**Comment by byndcivilization** [comment]
This is because i'm forcing the standardised metadata issue. I really think we need to eat our own dog food here. So I've given you all the condensed document type list for researchers and reviewers, However admins will have the appropriate, correct and full document type list which you will need to use when you clean up the document metadata. Statute is the type used across all the citation managment api's I can find. Likewise with the rest of the list.

**Comment by byndcivilization** [comment]
If you really want researchers to see the custom type, i can create some logic that renders these that way.

**Comment by isabellee** [comment]
It would be nice to have it display the specific reference type but I guess this can come at a later date.

**Comment by byndcivilization** [comment]
I don't understand what you mean. The issue here is that in every other citation data format legislation is either called bill or statute depending on if it's law or not. We're not in the business of citation management so we should defer to data standards. We can't on the consultant side because we worry they will get confused. But the underlying data us still adhering. This means that even though a researcher selects legislation, the tool is assigning the correct data type statute.  
I can set set some logic that says if type is statute, show a researcher legislation.

**Comment by byndcivilization** [comment]
In non-supervisor role, the types of documents are simplified. This is to make it easier for researcher/reviewers while also not breaking possible integrations with citation management services like Mendeley. We need some conditional formatting on researcher/reviewer biblio displays so that the doc types they see will match what they selected. The case mentioned above, the simplified label is legislation, while the accepted field name is statute. so in the case if user is not supervisor and type is statute - > label is "Legislation". Lets start there and deal down the road where the supervisor final doc type choice doesnt exist for a general user.
