### ISSUE TITLE
webpage upload hangs on certain sites

### ISSUE THREAD

**Issue by byndcivilization** [NRGI/rgi-assessment-tool#290]
not working for:
- http://www.dailymail.co.uk/ushome/index.html
- http://www.bbc.com

intermitantly working
- http://www.jotform.com
- http://www.imf.org

I think this is a timeout issue but its not sending an error.

**Comment by gjacovella** [comment]
Ok it doesn't work with the following links:
http://www.mining.com/infographic-how-the-mining-boom-has-impacted-b-c-31363/
https://76design.com/take-charge-mining-career/

But it works with other articles/web pages from the Guardian

**Comment by HumairaP** [comment]
It has worked for me today - for the first time.

**Comment by HumairaP** [comment]
It did not work for me when I tried to upload : http://www.theguardian.com/global-development/2016/mar/07/bananas-bleak-future-staple-african-crops-decline-beans-protein

**Comment by HumairaP** [comment]
Did not work on this link: http://www.theguardian.com/world/middleeast

**Comment by HumairaP** [comment]
I tried to upload the iranian ministry of petroleum's website but was shown this:

![image](https://cloud.githubusercontent.com/assets/17277178/13598425/9bf5cc42-e515-11e5-8d6f-b78d80b3b6f4.png)

**Comment by HumairaP** [comment]
However, I was able to upload the saudi ministry of petroleum's site - It's in arabic, whereas the iranian one is in Farsi.  Do you think it has anything to do with the language used or that it's just the website in general?

![image](https://cloud.githubusercontent.com/assets/17277178/13598846/fcea6a6a-e517-11e5-8fbb-d2f778941b87.png)

**Comment by byndcivilization** [comment]
No. Non ascii is supported so  scripts aren't throwing error

**Comment by gjacovella** [comment]
I just tried 3 different links (2 from Wikipedia and one from a magazine) and I couldn't create a webpage. However, I was able to create webpages up until 10 minutes ago
![image](https://cloud.githubusercontent.com/assets/16592996/13603151/0c8a565e-e533-11e5-86cf-06139507292a.png)

**Comment by gjacovella** [comment]
now it says that the URL is not available 
![image](https://cloud.githubusercontent.com/assets/16592996/13603459/3fdc2968-e535-11e5-8377-ddb0488a5751.png)

**Comment by byndcivilization** [comment]
Okay can recreate. Will chase down when I'm in. I'm wondering if one or both of these are caused by technology to stop pirating or aggregation.

**Comment by gjacovella** [comment]
Thank you!

**Comment by alexander-elgin** [comment]
The issues are caused by failure in processing of external JS by PhantomJS. For me it even crashes the server

**Comment by alexander-elgin** [comment]
snapshot file generating is synchronized with the transfer to S3, timeout introduced, empty pages are processed in https://github.com/NRGI/rgi-assessment-tool/pull/388

**Comment by alexander-elgin** [comment]
After increasing timeout up to **240 seconds** snapshots of the following URLs cannot be generated:
1. http://www.mining.com/infographic-how-the-mining-boom-has-impacted-b-c-31363/
2. http://www.dailymail.co.uk/ushome/index.html
3. http://www.theatlantic.com/magazine/archive/2012/11/the-end-of-jazz/309112/

Actually the pages continue to load content data (mostly images) once the page is rendered. Significant time is required for that.
Snapshots of the following URLs are successfully generated:
1. https://76design.com/take-charge-mining-career/
2. http://www.imf.org/
3. http://www.jotform.com/
4. http://mop.ir/Portal/Home/

Snapshot generating of the following pages was stopped because of the page dimensions:
1. http://www.theguardian.com/global-development/2016/mar/07/bananas-bleak-future-staple-african-crops-decline-beans-protein
2. http://www.bbc.com/

The following URLs are really unavailable for me (I cannot open them in my browser either):
1. http://www.ncbi.nim.nih.gov/pmc/articles/PMC4267093/
