### ISSUE TITLE
When a pick a final score, the next question is always Q. 138.7 (it keeps jumping to this question).

### ISSUE THREAD

**Issue by gjacovella** [NRGI/rgi-assessment-tool#327]

**Comment by HumairaP** [comment]
The same is happening for me, regardless of which precept I am working on.

**Comment by byndcivilization** [comment]
for researdchers and reviewers?

**Comment by gjacovella** [comment]
For the admin

**Comment by HumairaP** [comment]
For example, I was working on question 144.8 and it jumped to 138.7 when I had marked it as finalised.

**Comment by byndcivilization** [comment]
I think this is an issue with the updated navigation to handle dependant questions. We scrapped dependant questions at the last minute because modelling proved to complex so i had to triage this navigation as much as possible back to the original simple nav. We need to either update the improved nav to remove the dependant question stuff or move everything back to the simplified old way.

**Comment by alexander-elgin** [comment]
For me there is a redirect to the page 'Assessment Details' where I see the answers grouped by precepts. Is it the same for you now? Is this behavior correct or I should change it to navigate to the next question?

**Comment by byndcivilization** [comment]
The redirect to assessment detail should only be on the trial version. The correct behaviour should be to just move to the next question.

**Comment by alexander-elgin** [comment]
In the actual state of the `dev` branch after selecting the final score there is a redirect to the assessment details page (independently of the assessment status).

**Comment by alexander-elgin** [comment]
@byndcivilization I changed the behavior in https://github.com/NRGI/rgi-assessment-tool/pull/378 like it is described in your last comment
