### ISSUE TITLE
"Complete answer" answer button does not work correctly

### ISSUE THREAD

**Issue by ion-alecsandri** [NRGI/rgi-assessment-tool#453]
log in as research.
go to any answer, first ,click  "Complete answer" button.
Even though option is selected, it says "You must pick score".
![6](https://cloud.githubusercontent.com/assets/15853986/15186056/36ac7b9e-17a4-11e6-8e76-b4ac51d3a2b9.png)

if you save button, and click "Complete answer" button, then it works.

**Comment by alexander-elgin** [comment]
@ion-alecsandri I've tried to reproduce the issue using the directions that you provided, but I failed. I've never seen the error message 'You need pick a score'.

**Comment by alexander-elgin** [comment]
@ion-alecsandri Please, can you provide a detailed description of the test scenario steps to reproduce the issue? I cannot reproduce the issue using the directions you provided.

**Comment by ion-alecsandri** [comment]
That is strange.
Now I can not reproduce this error, too.
Perhaps it seems like that it was accident.

**Comment by alexander-elgin** [comment]
@ion-alecsandri In the recent time there were a lot of bug reports from you without test case scenario. Most of them were not submitted for further processing because they did not report about the actual issues. However some time was spent to figure it out. Please, before submitting a report
1. Create a clear and detailed test case scenario. Using the scenario everyone should be able to reproduce the issue.
2. Check the scenario by yourself. Be sure that the sequence of actions that you described really leads to a BUG.

Without a test case scenario I cannot reproduce the issue. If I cannot reproduce the issue I cannot fix it either.
